apiVersion: v1
kind: Route
metadata:
  labels:
    name: svc1
  name: svc1-route-unsecured
  namespace: default
  annotations:
    # Optionally specify the source address translation type of the virtual server
    virtual-server.f5.com/source-addr-translation: |
        {
          "type": "automap"
        }
spec:
  host: svc1-route.local
  path: "/test"
  port:
    targetPort: 80
  to:
    kind: Service
    name: svc1
