kind: ConfigMap
apiVersion: v1
metadata:
  name: example-vs
  namespace: default
  labels:
    f5type: virtual-server
data:
  schema: "f5schemadb://bigip-virtual-server_v0.1.7.json"
  # This assumes that a snat pool example-snat has been preconfigured in the Common partition
  data: |
    {
      "virtualServer": {
        "frontend": {
          "balance": "round-robin",
          "mode": "http",
          "partition": "kubernetes",
          "virtualAddress": {
            "bindAddr": "1.2.3.4",
            "port": 443
          },
          "sslProfile": {
            "f5ProfileName": "Common/testcert"
          },
          "sourceAddressTranslation": {
            "type": "snat",
            "pool": "/Common/example-snat"
          }
        },
        "backend": {
          "serviceName": "example-service",
          "servicePort": 443
        }
      }
    }
